name: CD Homolog

on:
  push:
    branches: [ deploy ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script: |
          mkdir teste
          cd teste
          touch funfou
